deploy:
  runs-on: ubuntu-latest
  needs: build
  if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

  steps:
    - name: Test server port
      run: |
        nc -vz ${{ secrets.SERVER_HOST }} ${{ secrets.SERVER_PORT }}
